# Generated by Django 2.2.4 on 2020-01-20 22:47

from django.db import migrations, models


def type_build(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_build = True
        else:
            flat.new_build = False
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_build'),
    ]


    operations = [
        migrations.RunPython(type_build),
    ]

