# Generated by Django 2.2.4 on 2020-01-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200121_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='new_build',
            new_name='new_building',
        ),
    ]
