# Generated by Django 2.2.4 on 2020-01-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200121_0213'),
    ]

    operations = [
    ]
