# Generated by Django 2.2.4 on 2020-01-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200121_2156'),
    ]

    operations = [
    ]
