# Generated by Django 2.2.4 on 2020-01-21 20:42

from django.db import migrations
import phonenumbers

def phone_pure(apps,shema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(owners_phone='+70000000000'):
        owners_phone = flat.owners_phonenumber
        if phonenumbers.is_valid_number(owners_phone):
            number = phonenumbers.parse(owners_phone, 'RU')
            formated_number = phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.owner_phone_pure = formated_number
            flat.save()
        else:
            flat.owner_phone_pure = None
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200121_2327'),
    ]

    operations = [
        migrations.RunPython(phone_pure)
    ]
